name: galaxy_warrior
description: "Galaxy Warrior Game with AdMob"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - ./
