name: galaxy_warrior
description: "Galaxy Warrior Game with AdMob"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  webview_flutter: ^4.10.0

flutter:
  uses-material-design: true
  assets:
    - index.html
    - plane1.png
    - plane2.png
    - plane3.png
    - obscle.png
    - boss.png
    - bullet.png
    - bg.png
    - bullet.wav
    - bgm.wav
